# -*- coding: utf-8 -*-
"""assignment_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3F4cLoFa6q101ww9qujHr_ZmR3F-1-v
"""

import pandas as pd

import pymc as pm

import arviz as az

import matplotlib.pyplot as plt



# Load the data

data = 'https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/cookie_cats.csv'

df = pd.read_csv(data)



# Preview data

print(df.head())



df['retention1'] = df['retention_1'].astype(int)

df['retention7'] = df['retention_7'].astype(int)



# Separate data by group (a = gate_30, control, and b = gate_40, moved)

a_gate_30 = df[df['version'] == 'gate_30']

b_gate_40 = df[df['version'] == 'gate_40']



def bayesian_ab_test(success_a, total_a, success_b, total_b, group_label="1-day Retention"):

    with pm.Model() as model:

        # Prior distributions for the two groups' retention rates

        p_a = pm.Beta('p_a', alpha=1, beta=1)

        p_b = pm.Beta('p_b', alpha=1, beta=1)



        # Likelihood for observed data

        obs_a = pm.Binomial('obs_a', n=total_a, p=p_a, observed=success_a)

        obs_b = pm.Binomial('obs_b', n=total_b, p=p_b, observed=success_b)



        # Define difference in proportions

        delta = pm.Deterministic('delta', p_b - p_a)



        # Sample from the posterior

        trace = pm.sample(2000, tune=1000, return_inferencedata=True)



    # Plot posterior distribution

    az.plot_posterior(trace, var_names=['delta'], ref_val=0, hdi_prob=0.95)

    plt.title(f"Posterior of Difference in {group_label}")

    plt.show()



    summary = az.summary(trace, hdi_prob=0.95)

    print(summary.loc[['p_a', 'p_b', 'delta']])

    return summary.loc['delta']



# Run for 1-day retention

delta1 = bayesian_ab_test(

    success_a=a_gate_30['retention1'].sum(),

    total_a=len(a_gate_30),

    success_b=b_gate_40['retention1'].sum(),

    total_b=len(b_gate_40),

    group_label="1-day Retention"

)



# Run for 7-day retention

delta7 = bayesian_ab_test(

    success_a=a_gate_30['retention7'].sum(),

    total_a=len(a_gate_30),

    success_b=b_gate_40['retention7'].sum(),

    total_b=len(b_gate_40),

    group_label="7-day Retention"

)

"""ou will be asked to answer the following questions in a small quiz on Canvas:

1)What was the effect of moving the gate from level 30 to level 40 on 1-day retention rates?
--Moving the gate lowered 1 day retention

2)What was the effect of moving the gate from level 30 to level 40 on 7-day retention rates?

--Moving the gate lowered 7 day retention

3)What was the biggest challenge for you in completing this assignment?
-Understanding how to interpret the summary statistics. Specifically when it comes to HDI
"""